### ISSUE TITLE
Evolve config structure 

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop-clients#38]
The goal here is to organize the config in a way that someone can look at it and get an idea of how the script is configured to work. 

Here is one idea of how that _might_ look-

```
streams: 
  CSB:
    type: granule
    prefix: NESDIS/CSB
    collection_id : 'fdb56230-87f4-49f2-ab83-104cfd073177'
    duplicate_region: us-east-1
    archive: false
  SAB:
    type: granule
    prefix: NESDIS/H8
    collection_id: 98e03b47-069a-4f2c-8071-649e8c4254d6
  GOES: 
    type: granule
    prefix: NESDIS/GOES
    collection_id: 'fdb56230-87f4-49f2-ab83-104cfd073177'
  H8:
    prefix: NESDIS/H8

aws:
  sqs:
    url: https://sqs.us-east-2.amazonaws.com/798276211865/cloud-archive-client-sqs
    max_polls: 10
  s3:
    bucket:  noaa-nccf-dev-archive

onestop:
  registry:
    url: http://onestop-registry:80
  search:
    url:  http://onestop-search:8080
    
log:
  level: INFO
```
